
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
	SELECT * 
	FROM books
	WAITFOR DELAY '00:00:05'
	SELECT * 
	FROM books
COMMIT TRAN


SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
	SELECT * 
	FROM books
	WAITFOR DELAY '00:00:05'
	SELECT * 
	FROM books
COMMIT TRAN