--T2

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN
	SELECT *
	FROM categories
COMMIT TRAN

--solution
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
	SELECT *
	FROM categories
COMMIT TRAN